# This file configures your Hugging Face Space.
# For most Gradio apps, you do NOT need to edit this file.
# You can set environment variables, secrets, and hardware here if needed.

# Example: Set the title and SDK
sdk: gradio
app_file: app.py

# Uncomment and edit below if you want to set secrets or environment variables
# secrets:
#   GROQ_API_KEY: your-groq-api-key-here

# Uncomment to request a GPU (not needed for this app)
# hardware:
#   accelerator: cpu

# For more info: https://huggingface.co/docs/hub/spaces-config-reference
